debug: true

github:
  client-secret: ENC(IAU4rBl5whtgBDbDikyfHHQIzQPMOU5CZsFtH3NdnZ4jtHC8SEd5gBMsRh+65tqPgI18jpcEbaXlEbGk6MNSXm726SNfGdu2wVCcyW8Pu4o=)

spring:
  profiles:
    active: local
---
spring:
  profiles: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
    url: ENC(5ztirr1z9ySsifA27076fd3AqYnGQzs4YptRKJYKmSY6JZ9RXFr4xX8lYjCdElP9LCxUi4Bz6zigTB9JIZ1XTfO4w5RBgFI/310i0gcwy2csx6mmZh6Vwx9T0P7AGw7m07C8/FahF6ijA+6zDEQ5jA==)
    username: ENC(C/v+MxWkykIVlo4VoxdaeIutJnv6bI9sWjd9I8bdWR2jtWddqWbc1dDQecntYAEW)
    password: ENC(Rrum2OUG0ImkBXCH+3BxKUqjc3KErfGq8P5HtTZKBPFi60OiB4g1xL3xALL5Cb1g)
---
spring:
  profiles:
    active: server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
    url: ENC(L7/xh3T2aYNL6Yee92ZTI9Pbj/OEsQs3VzP73CpnUlLPUvVovTXZ9JAr3LalwTvM0qg0aPYYdkeT/+LVlKc1uYy9FdJzzL2vPGEtZxlsBbN83YSQ806dCpzxFy0g1tyGMR56wKU71pgzx2y8Mai1V/dTx6IHdUXPJEr8RguqU+E=)
    username: ENC(2jGWruPjt0fCKiwuJ4BwChkoBJDezzO7pJZ5fDYRLY3uD4oX5Rdeqf9hjBA9qD6e)
    password: ENC(UGJJv87CQdNE6roamjQaU+s9HvDwI6N/A/YHFzF0cZTjA1wHY5/IsMoWoQLhVgmr)
